name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mariuszkopacz/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mariuszkopacz/react-test npm test

      - run: docker build -t mariuszkopacz/multi-client ./client
      - run: docker build -t mariuszkopacz/multi-nginx ./nginx
      - run: docker build -t mariuszkopacz/multi-server ./server
      - run: docker build -t mariuszkopacz/multi-worker ./worker

      - run: docker push mariuszkopacz/multi-client
      - run: docker push mariuszkopacz/multi-nginx
      - run: docker push mariuszkopacz/multi-server
      - run: docker push mariuszkopacz/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-167400438762
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
